import { useState, useEffect, useRef } from 'react';
import { getDistance, calculateBearing } from '../utils/mapUtils';

interface LocationState {
    loaded: boolean;
    coordinates?: { lat: number; lng: number };
    heading?: number | null;
    speed?: number | null;
}

export const useSimulatedLocation = (
    routeCoords: [number, number][] | null, // [lat, lng]
    isActive: boolean,
    speedKmh: number = 20
) => {
    const [location, setLocation] = useState<LocationState>({ loaded: false });
    const currentSegmentIndexRef = useRef(0);
    const segmentProgressMetersRef = useRef(0);
    const lastTimeRef = useRef<number>(0);
    const requestRef = useRef<number>(0);

    useEffect(() => {
        if (!isActive || !routeCoords || routeCoords.length < 2) {
            cancelAnimationFrame(requestRef.current);
            return;
        }

        // Automatically reset progress if it's a completely new route (first frame)
        // or just ensure we start fresh. However, since routeCoords might be new,
        // let's just reset when current index is 0. 
        if (currentSegmentIndexRef.current === 0 && segmentProgressMetersRef.current === 0) {
            setLocation({
                loaded: true,
                coordinates: { lat: routeCoords[0][0], lng: routeCoords[0][1] },
                heading: 0,
                speed: speedKmh // Initialize with non-zero to break deadlock
            });
        }

        lastTimeRef.current = performance.now();

        const animate = (time: number) => {
            const deltaTime = (time - lastTimeRef.current) / 1000; // seconds
            lastTimeRef.current = time;

            // Guard against massive frame skips causing teleports
            if (deltaTime > 0 && deltaTime < 0.2) {
                if (!moveAlongRoute(deltaTime)) return;
            }

            requestRef.current = requestAnimationFrame(animate);
        };

        const moveAlongRoute = (deltaTime: number) => {
            if (currentSegmentIndexRef.current >= routeCoords.length - 1) {
                // Simulation reached destination: kill speed to gracefully halt dashboard instruments
                setLocation(prev => ({ ...prev, speed: 0 }));
                return false;
            }

            // Sync mechanical simulation speed to the dynamic AI profile generated by the Dashboard! 
            let activeSpeedKmh = speedKmh;
            if (typeof (window as any).__vSpeed === 'number') {
                activeSpeedKmh = (window as any).__vSpeed;
            }

            let speedModifier = 6.0; // Global multiplier to make the simulation progress at an engaging pace
            
            // Heuristic to make simulation slow during sharp turns and faster during long straight roads
            if (currentSegmentIndexRef.current < routeCoords.length - 1) {
                const p1 = routeCoords[currentSegmentIndexRef.current];
                const p2 = routeCoords[currentSegmentIndexRef.current + 1];
                const segDist = getDistance(p1[0], p1[1], p2[0], p2[1]);
                
                if (currentSegmentIndexRef.current < routeCoords.length - 2) {
                    const p3 = routeCoords[currentSegmentIndexRef.current + 2];
                    const bearing1 = calculateBearing(p1[0], p1[1], p2[0], p2[1]);
                    const bearing2 = calculateBearing(p2[0], p2[1], p3[0], p3[1]);
                    
                    let angleDiff = Math.abs(bearing1 - bearing2);
                    if (angleDiff > 180) angleDiff = 360 - angleDiff;
                    
                    if (angleDiff > 45) {
                        speedModifier *= 0.3; // Slow down significantly for sharp turns
                    } else if (angleDiff > 20) {
                        speedModifier *= 0.6; // Moderate slowdown for slight curves
                    } else if (segDist > 100) {
                        speedModifier *= 2.0; // Speed up extensively on long straight segments
                    } else if (segDist > 50) {
                        speedModifier *= 1.3;
                    }
                } else if (segDist > 50) {
                    speedModifier *= 1.5;
                }
            }

            const speedMs = ((activeSpeedKmh * speedModifier) * 1000) / 3600;
            let distToMove = speedMs * deltaTime; // exact meters to move this frame

            // Follow the segments exactly using geographic distance
            while (distToMove > 0 && currentSegmentIndexRef.current < routeCoords.length - 1) {
                const p1 = routeCoords[currentSegmentIndexRef.current];
                const p2 = routeCoords[currentSegmentIndexRef.current + 1];
                
                const segDist = getDistance(p1[0], p1[1], p2[0], p2[1]);
                const remainingInSeg = segDist - segmentProgressMetersRef.current;

                if (distToMove <= remainingInSeg || segDist === 0) {
                    segmentProgressMetersRef.current += distToMove;
                    distToMove = 0; // Exhausted movement capability
                    
                    const t = segDist === 0 ? 1 : segmentProgressMetersRef.current / segDist;
                    const lat = p1[0] + (p2[0] - p1[0]) * t;
                    const lng = p1[1] + (p2[1] - p1[1]) * t;
                    
                    // Simple accurate bearing calculation
                    let bearing = location.heading || 0;
                    if (segDist > 0) {
                        const dLon = (p2[1] - p1[1]) * Math.PI / 180;
                        const lat1 = p1[0] * Math.PI / 180;
                        const lat2 = p2[0] * Math.PI / 180;
                        const y = Math.sin(dLon) * Math.cos(lat2);
                        const x = Math.cos(lat1) * Math.sin(lat2) - Math.sin(lat1) * Math.cos(lat2) * Math.cos(dLon);
                        bearing = (Math.atan2(y, x) * 180 / Math.PI + 360) % 360;
                    }

                    setLocation({
                        loaded: true,
                        coordinates: { lat, lng },
                        heading: bearing,
                        speed: speedKmh
                    });
                } else {
                    // Carry over remaining distance to next segment
                    distToMove -= remainingInSeg;
                    currentSegmentIndexRef.current++;
                    segmentProgressMetersRef.current = 0;
                }
            }
            
            return true; // Continue animation loop
        };

        requestRef.current = requestAnimationFrame(animate);

        return () => cancelAnimationFrame(requestRef.current);
    }, [isActive, routeCoords, speedKmh]); // Depend on dependencies properly

    const resetSimulation = () => {
        currentSegmentIndexRef.current = 0;
        segmentProgressMetersRef.current = 0;
    };

    return { ...location, resetSimulation };
};
